# Generated by Django 4.1.2 on 2022-10-25 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car", name="year", field=models.CharField(max_length=50),
        ),
    ]
