# Generated by Django 4.1.2 on 2022-10-25 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0003_alter_car_year_alter_customer_age"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employee_id", models.CharField(max_length=10)),
                ("name", models.CharField(max_length=50)),
                ("address", models.CharField(max_length=50)),
                ("branch", models.CharField(max_length=50)),
            ],
        ),
    ]
